### ISSUE TITLE
Windows Terminal port

### ISSUE THREAD

**Issue by obvRedwolf** [eldritch-theme/eldritch#13]

**Comment by obvRedwolf** [comment]
got it done, just waiting for someone to create repository

![image](https://github.com/eldritch-theme/eldritch/assets/71992659/5949d741-d9b0-490c-b4b8-dc8ec58cf06a)

**Comment by jacobrreed** [comment]
Invited you to org. You should be able to create a repo

**Comment by obvRedwolf** [comment]
> Invited you to org. You should be able to create a repo

thanks!

**Comment by jacobrreed** [comment]
Work complete, needs repo moved to Public and main repo README updated
