### ISSUE TITLE
Fastfetch port.

### ISSUE THREAD

**Issue by obvRedwolf** [eldritch-theme/eldritch#18]

**Comment by jacobrreed** [comment]
What do you mean by theme for this, I assume it's like neofetch and will just use terminal colors

**Comment by obvRedwolf** [comment]
dont we need to port the format over?

**Comment by jacobrreed** [comment]
Fastfetch, neofetch, etc all use terminal colors. So if a user is using one or our terminal themes they'll be good to go. Unless you mean ASCII art for fetch, but the colors are term colors
