### ISSUE TITLE
iTerm2 implementation

### ISSUE THREAD

**Issue by mikl** [eldritch-theme/eldritch#24]
I’ve ported Eldritch to iTerm2: https://github.com/mikl/eldritch-iterm2

We can keep it there, or move it to this org, let me know what you prefer.

**Comment by jacobrreed** [comment]
ya let's move it in!

**Comment by jacobrreed** [comment]
I sent you an invite to organization after transfer I'll make you admin for that repo thanks @mikl

**Comment by mikl** [comment]
Alright, repo moved: https://github.com/eldritch-theme/iterm2

**Comment by jacobrreed** [comment]
thanks, made you admin for that repo, also added to main readme already

**Comment by mikl** [comment]
Great, thanks for creating this theme.
