### ISSUE TITLE
fish/fish_themes port

### ISSUE THREAD

**Issue by ProspectPyxis** [eldritch-theme/eldritch#27]
Just found out about this theme recently and I love it - thank you for making it!

I'd like an integration with fish, a CLI shell. I already have the theme applied to my terminal emulator, but with the default settings, the autocomplete suggestions are so dark it's almost unreadable:
![image](https://github.com/user-attachments/assets/937ba1bd-e948-4754-91a0-1f10c69eb208)

A fish-specific theme would fix this.

Examples:
https://github.com/folke/tokyonight.nvim/blob/main/extras/fish_themes/tokyonight_night.theme
https://github.com/scottmckendry/cyberdream.nvim/blob/main/extras/fish/cyberdream.theme

I'd be willing to make a contribution for this.

**Comment by jacobrreed** [comment]
Go for it!

**Comment by ProspectPyxis** [comment]
[The theme is created!](https://github.com/ProspectPyxis/fish-theme)

I'd like to transfer this repo to the eldritch-theme organization, if possible.

From the screenshot, please let me know if any changes are wanted.

**Comment by jacobrreed** [comment]
> [The theme is created!](https://github.com/ProspectPyxis/fish-theme)
> 
> I'd like to transfer this repo to the eldritch-theme organization, if possible.
> 
> From the screenshot, please let me know if any changes are wanted.
> 
> 

Looks good, request transfer

**Comment by jacobrreed** [comment]
After you transfer, please open a PR to main repo updating README

**Comment by ProspectPyxis** [comment]
> Looks good, request transfer

Sorry, I'm kinda new to this - how would I go about this? Trying to transfer the repo directly tells me I don't have permission to create public repos for the organization.

**Comment by jacobrreed** [comment]
> > Looks good, request transfer
> 
> Sorry, I'm kinda new to this - how would I go about this? Trying to transfer the repo directly tells me I don't have permission to create public repos for the organization.

Invited you to org
