### ISSUE TITLE
Hyprpanel

### ISSUE THREAD

**Issue by DWarez** [eldritch-theme/eldritch#31]
Hi, I quickly created [this repository](https://github.com/DWarez/eldritch-hyprpanel) for Hyprpanel, which is a bar/panel for Hyprland.

I was trying to make a PR by creating a new branch and updating the readme, but it seems I don't have the access rights to do so.

Feel free to integrate the link in the readme if you find it useful.

**Comment by jacobrreed** [comment]
Ya usually if you want to PR you need to fork, then open PR. I can do for you if you'd like, I'll probably add another section for things like this

**Comment by DWarez** [comment]
sure, go for it :smile:
